/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha3

import (
	bootstrapv1alpha2 "github.com/openshift-assisted/cluster-api-provider-openshift-assisted/bootstrap/api/v1alpha2"
	hiveext "github.com/openshift/assisted-service/api/hiveextension/v1beta1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	clusterv1 "sigs.k8s.io/cluster-api/api/core/v1beta2"
)

const InstallConfigOverrideAnnotation = "controlplane.cluster.x-k8s.io/install-config-override"

type OpenshiftAssistedControlPlaneMachineTemplate struct {
	// Standard object's metadata.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	// +optional
	ObjectMeta clusterv1.ObjectMeta `json:"metadata,omitempty"`

	// InfrastructureRef is a required reference to a custom resource
	// offered by an infrastructure provider.
	InfrastructureRef clusterv1.ContractVersionedObjectReference `json:"infrastructureRef"`

	// Deletion contains configuration options for Machine deletion.
	// +optional
	// +kubebuilder:default={nodeDeletionTimeoutSeconds: 10}
	Deletion clusterv1.MachineDeletionSpec `json:"deletion,omitempty"`
}

// OpenshiftAssistedControlPlaneSpec defines the desired state of OpenshiftAssistedControlPlane
type OpenshiftAssistedControlPlaneSpec struct {
	// Config contains configuration specs for the OpenshiftAssistedControlPlane
	Config                      OpenshiftAssistedControlPlaneConfigSpec       `json:"config,omitempty"`
	MachineTemplate             OpenshiftAssistedControlPlaneMachineTemplate  `json:"machineTemplate"`
	OpenshiftAssistedConfigSpec bootstrapv1alpha2.OpenshiftAssistedConfigSpec `json:"openshiftAssistedConfigSpec,omitempty"`
	Replicas                    int32                                         `json:"replicas,omitempty"`
	// DistributionVersion describes the targeted OpenShift version
	DistributionVersion string `json:"distributionVersion"`
}

// OpenshiftAssistedControlPlaneConfigSpec defines configuration for the agent-provisioned cluster
type OpenshiftAssistedControlPlaneConfigSpec struct {
	// From AgentClusterInstall https://github.com/openshift/assisted-service/blob/master/api/hiveextension/v1beta1/agentclusterinstall_types.go

	// Platform specifies the infrastructure platform type for the cluster.
	// Valid values are: BareMetal (default), External, KubeVirt.
	// When set to External or KubeVirt, Metal3-specific behaviors are disabled.
	// +kubebuilder:validation:Enum=BareMetal;External;KubeVirt
	// +kubebuilder:default=BareMetal
	// +optional
	Platform PlatformType `json:"platform,omitempty"`

	// KubeVirt contains platform-specific configuration for the KubeVirt infrastructure provider.
	// Only used when Platform is set to KubeVirt.
	// +optional
	KubeVirt *KubeVirtPlatformSpec `json:"kubevirt,omitempty"`

	// APIVIPs are the virtual IPs used to reach the OpenShift cluster's API.
	// Enter one IP address for single-stack clusters, or up to two for dual-stack clusters (at
	// most one IP address per IP stack used). The order of stacks should be the same as order
	// of subnets in Cluster Networks, Service Networks, and Machine Networks.
	// +kubebuilder:validation:MaxItems=2
	// +optional
	APIVIPs []string `json:"apiVIPs,omitempty"`

	// IngressVIPs are the virtual IPs used for cluster ingress traffic.
	// Enter one IP address for single-stack clusters, or up to two for dual-stack clusters (at
	// most one IP address per IP stack used). The order of stacks should be the same as order
	// of subnets in Cluster Networks, Service Networks, and Machine Networks.
	// +kubebuilder:validation:MaxItems=2
	// +optional
	IngressVIPs []string `json:"ingressVIPs,omitempty"`

	// ManifestsConfigMapRefs is an array of references to user-provided manifests ConfigMaps to
	// add to or replace manifests that are generated by the installer.
	// Manifest names in each ConfigMap should be unique across all referenced ConfigMaps.
	// +optional
	ManifestsConfigMapRefs []hiveext.ManifestsConfigMapReference `json:"manifestsConfigMapRefs,omitempty"`

	// DiskEncryption is the configuration to enable/disable disk encryption for cluster nodes.
	// +optional
	DiskEncryption *hiveext.DiskEncryption `json:"diskEncryption,omitempty"`

	// Proxy defines the proxy settings used for the install config
	// +optional
	Proxy *hiveext.Proxy `json:"proxy,omitempty"`

	// Set to true to allow control plane nodes to be schedulable
	// +optional
	MastersSchedulable bool `json:"mastersSchedulable,omitempty"`

	// SSHAuthorizedKey ssh key for accessing the cluster nodes after reboot
	SSHAuthorizedKey string `json:"sshAuthorizedKey,omitempty"`

	// From ClusterDeployment

	// ClusterName is the friendly name of the cluster. It is used for subdomains,
	// some resource tagging, and other instances where a friendly name for the
	// cluster is useful.
	// If not defined ClusterName will be set as the CAPI ClusterName
	// +optional
	ClusterName string `json:"clusterName"`

	// BaseDomain is the base domain to which the cluster should belong.
	// +required
	BaseDomain string `json:"baseDomain"`

	// PullSecretRef references pull secret necessary for the cluster installation
	PullSecretRef *corev1.LocalObjectReference `json:"pullSecretRef,omitempty"`

	// ImageRegistryRef is a reference to a configmap containing both the additional
	// image registries and their corresponding certificate bundles to be used in the spoke cluster
	ImageRegistryRef *corev1.LocalObjectReference `json:"imageRegistryRef,omitempty"`

	// Capabilities specifies the capabilities set during an OpenShift cluster installation.
	Capabilities Capabilities `json:"capabilities,omitempty"`
}

type Capabilities struct {
	// BaselineCapability provides a default set of capabilities to enable during the installation.
	// Valid values are vCurrent, v4.x, or None. See the OpenShift doc for more details.
	// Defaults to None for baremetal platform workload clusters or vCurrent otherwise.
	// +optional
	BaselineCapability string `json:"baselineCapability,omitempty"`

	// AdditionalEnabledCapabilities is a list of OpenShift capabilities to specifically enable
	// during the installation of the workload cluster. It is empty by default.
	// +optional
	AdditionalEnabledCapabilities []string `json:"additionalEnabledCapabilities,omitempty"`
}

// OpenshiftAssistedControlPlaneInitializationStatus provides observations of the OpenshiftAssistedControlPlane initialization process.
// +kubebuilder:validation:MinProperties=1
type OpenshiftAssistedControlPlaneInitializationStatus struct {
	// controlPlaneInitialized is true when the OpenshiftAssistedControlPlane provider reports that the Kubernetes control plane is initialized;
	// A control plane is considered initialized when it can accept requests, no matter if this happens before
	// the control plane is fully provisioned or not.
	// NOTE: this field is part of the Cluster API contract, and it is used to orchestrate initial Machine provisioning.
	// +optional
	ControlPlaneInitialized *bool `json:"controlPlaneInitialized,omitempty"`
}

type OpenshiftAssistedControlPlaneStatus struct {
	// conditions represents the observations of a OpenshiftAssistedControlPlane's current state.
	// Known condition types are Available, CertificatesAvailable, EtcdClusterAvailable, MachinesReady, MachinesUpToDate,
	// ScalingUp, ScalingDown, Remediating, Deleting, Paused.
	// +optional
	// +listType=map
	// +listMapKey=type
	// +kubebuilder:validation:MaxItems=32
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// initialization provides observations of the OpenshiftAssistedControlPlane initialization process.
	// NOTE: Fields in this struct are part of the Cluster API contract and are used to orchestrate initial Machine provisioning.
	// +optional
	Initialization OpenshiftAssistedControlPlaneInitializationStatus `json:"initialization,omitempty,omitzero"`

	// selector is the label selector in string format to avoid introspection
	// by clients, and is used to provide the CRD-based integration for the
	// scale subresource and additional integrations for things like kubectl
	// describe.. The string will be in the same format as the query-param syntax.
	// More info about label selectors: http://kubernetes.io/docs/user-guide/labels#label-selectors
	// +optional
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=4096
	Selector string `json:"selector,omitempty"`

	// replicas is the total number of non-terminated machines targeted by this control plane
	// (their labels match the selector).
	// +optional
	Replicas *int32 `json:"replicas,omitempty"`

	// readyReplicas is the number of ready replicas for this OpenshiftAssistedControlPlane. A machine is considered ready when Machine's Ready condition is true.
	// +optional
	ReadyReplicas *int32 `json:"readyReplicas,omitempty"`

	// availableReplicas is the number of available replicas targeted by this OpenshiftAssistedControlPlane. A machine is considered available when Machine's Available condition is true.
	// +optional
	AvailableReplicas *int32 `json:"availableReplicas,omitempty"`

	// upToDateReplicas is the number of up-to-date replicas targeted by this OpenshiftAssistedControlPlane. A machine is considered up-to-date when Machine's UpToDate condition is true.
	// +optional
	UpToDateReplicas *int32 `json:"upToDateReplicas,omitempty"`

	// version represents the minimum Kubernetes version for the control plane machines
	// in the cluster.
	// +optional
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=256
	Version string `json:"version,omitempty"`

	// DistributionVersion represents the current OpenShift version installed on the
	// control plane machines in the cluster.
	DistributionVersion string `json:"distributionVersion,omitempty"`

	// observedGeneration is the latest generation observed by the controller.
	// +optional
	// +kubebuilder:validation:Minimum=1
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion
// +kubebuilder:resource:shortName=oacp;oacps
// +kubebuilder:subresource:scale:specpath=.spec.replicas,statuspath=.status.replicas,selectorpath=.status.selector
// +kubebuilder:printcolumn:name="Cluster",type="string",JSONPath=".metadata.labels['cluster\\.x-k8s\\.io/cluster-name']",description="Cluster"
// +kubebuilder:printcolumn:name="Initialized",type=boolean,JSONPath=".status.initialization.controlPlaneInitialized",description="This denotes whether or not the control plane has been initialized"
// +kubebuilder:printcolumn:name="Desired",type=integer,JSONPath=".spec.replicas",description="Total number of machines desired by this control plane",priority=10
// +kubebuilder:printcolumn:name="Replicas",type=integer,JSONPath=".status.replicas",description="Total number of non-terminated machines targeted by this control plane"
// +kubebuilder:printcolumn:name="Ready",type=integer,JSONPath=".status.readyReplicas",description="Total number of fully running and ready control plane machines"
// +kubebuilder:printcolumn:name="Up-To-Date",type=integer,JSONPath=".status.upToDateReplicas",description="Total number of up-to-date replicas targeted by this control plane"
// +kubebuilder:printcolumn:name="Available",type=integer,JSONPath=".status.availableReplicas",description="Total number of available machines targeted by this control plane"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",description="Time duration since creation of OpenshiftAssistedControlPlane"
// +kubebuilder:printcolumn:name="Distribution Version",type=string,JSONPath=".spec.distributionVersion",description="OpenShift version associated with this control plane"

// OpenshiftAssistedControlPlane is the Schema for the openshiftassistedcontrolplane API
type OpenshiftAssistedControlPlane struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   OpenshiftAssistedControlPlaneSpec   `json:"spec,omitempty"`
	Status OpenshiftAssistedControlPlaneStatus `json:"status,omitempty"`
}

//+kubebuilder:object:root=true

// OpenshiftAssistedControlPlaneList contains a list of OpenshiftAssistedControlPlane
type OpenshiftAssistedControlPlaneList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OpenshiftAssistedControlPlane `json:"items"`
}

// PlatformType defines the infrastructure platform type for the cluster.
// +kubebuilder:validation:Enum=BareMetal;External;KubeVirt
type PlatformType string

const (
	// PlatformBareMetal indicates a bare-metal platform (Metal3/CAPM3).
	PlatformBareMetal PlatformType = "BareMetal"

	// PlatformExternal indicates an external platform (generic, no specific cloud integration).
	PlatformExternal PlatformType = "External"

	// PlatformKubeVirt indicates a KubeVirt platform (VMs on an existing cluster).
	PlatformKubeVirt PlatformType = "KubeVirt"
)

// KubeVirtPlatformSpec contains KubeVirt-specific platform configuration.
type KubeVirtPlatformSpec struct {
	// CloudControllerManager configures the KubeVirt cloud controller manager.
	// +optional
	CloudControllerManager *KubeVirtCCMSpec `json:"cloudControllerManager,omitempty"`

	// CSIDriver configures the storage driver for the tenant cluster.
	// +optional
	CSIDriver *KubeVirtCSISpec `json:"csiDriver,omitempty"`

	// InfraClusterCredentials references a Secret containing the kubeconfig for the
	// infra cluster where VMs run. This credential is injected into the tenant cluster
	// for use by KCCM and kubevirt-csi-driver operators.
	// +optional
	InfraClusterCredentials *corev1.LocalObjectReference `json:"infraClusterCredentials,omitempty"`

	// InfraClusterNamespace is the namespace on the infra cluster where tenant VMs reside.
	// +optional
	InfraClusterNamespace string `json:"infraClusterNamespace,omitempty"`

	// Networking contains KubeVirt VM networking configuration.
	// +optional
	Networking *KubeVirtNetworkingSpec `json:"networking,omitempty"`

	// ExternalAccess configures external access to the tenant cluster API and Ingress
	// via LoadBalancer Services on the infra cluster.
	// +optional
	ExternalAccess *KubeVirtExternalAccessSpec `json:"externalAccess,omitempty"`

	// RHCOSImageRegistry is the target container registry where the RHCOS kubevirt
	// ociarchive will be pushed as a container image for CDI to import.
	// Example: "quay.io/orenc/rhcos-kubevirt"
	// The tag is derived from the OCP version (e.g., "4.20").
	// +optional
	RHCOSImageRegistry string `json:"rhcosImageRegistry,omitempty"`

	// RHCOSImagePushSecret references a Secret with registry push credentials
	// (dockerconfigjson format) used by the RHCOS image publishing Job.
	// +optional
	RHCOSImagePushSecret *corev1.LocalObjectReference `json:"rhcosImagePushSecret,omitempty"`
}

// KubeVirtNetworkingMode specifies how VMs are attached to the network.
// +kubebuilder:validation:Enum=Bridge;Masquerade
type KubeVirtNetworkingMode string

const (
	// NetworkingModeBridge attaches VMs directly to the pod network via a bridge.
	// Each VM gets a unique, routable pod IP. Required for multi-node etcd quorum.
	NetworkingModeBridge KubeVirtNetworkingMode = "Bridge"

	// NetworkingModeMasquerade uses NAT for VM traffic (all VMs see the same internal IP).
	// Not suitable for multi-node control planes.
	NetworkingModeMasquerade KubeVirtNetworkingMode = "Masquerade"
)

// KubeVirtNetworkingSpec contains networking configuration for KubeVirt VMs.
type KubeVirtNetworkingSpec struct {
	// Mode specifies the VM networking mode. Defaults to Bridge.
	// Bridge mode is required for multi-node clusters (unique IPs needed for etcd).
	// +kubebuilder:default=Bridge
	// +optional
	Mode KubeVirtNetworkingMode `json:"mode,omitempty"`
}

// KubeVirtExternalAccessSpec configures external access to the tenant cluster.
type KubeVirtExternalAccessSpec struct {
	// APIPort is the external port for the tenant API server LoadBalancer.
	// Defaults to 6443. Set to 7443 when running on Azure (to avoid conflict
	// with the infra cluster's API on port 6443).
	// Only used when UseRoutes is false.
	// +kubebuilder:default=6443
	// +optional
	APIPort int32 `json:"apiPort,omitempty"`

	// IngressEnabled controls whether a LoadBalancer Service is created for
	// tenant cluster ingress (ports 80 and 443).
	// Only used when UseRoutes is false.
	// +optional
	IngressEnabled bool `json:"ingressEnabled,omitempty"`

	// UseRoutes enables Route-based external access instead of LoadBalancer services.
	// When true, passthrough OpenShift Routes are created on the infra cluster for
	// both API and ingress traffic, and services are created as ClusterIP type.
	// This requires the baseDomain to be a subdomain of the infra cluster's apps domain
	// (so that the existing wildcard DNS resolves tenant domains to the infra router).
	// Only applicable for pod-networking topologies where VMs are reachable via ClusterIP.
	// For host-network/Multus/NAD setups, leave this false and use LoadBalancer mode.
	// +optional
	UseRoutes bool `json:"useRoutes,omitempty"`
}

// KubeVirtCCMSpec configures the KubeVirt cloud controller manager operator.
type KubeVirtCCMSpec struct {
	// Enabled controls whether the kubevirt-cloud-controller-manager-operator
	// is deployed on the tenant cluster. Defaults to false.
	// Set to true for pod-network clusters that need LoadBalancer services.
	// +optional
	Enabled bool `json:"enabled,omitempty"`
}

// KubeVirtCSIDriverType defines the CSI driver deployment option.
// +kubebuilder:validation:Enum=KubeVirt;None;External
type KubeVirtCSIDriverType string

const (
	// CSIDriverKubeVirt deploys the kubevirt-csi-driver-operator on the tenant cluster.
	CSIDriverKubeVirt KubeVirtCSIDriverType = "KubeVirt"

	// CSIDriverNone disables CSI driver deployment; user manages storage independently.
	CSIDriverNone KubeVirtCSIDriverType = "None"

	// CSIDriverExternal indicates user-provided CSI manifests will be injected.
	CSIDriverExternal KubeVirtCSIDriverType = "External"
)

// KubeVirtCSISpec configures the CSI driver for the tenant cluster.
type KubeVirtCSISpec struct {
	// Type specifies the CSI driver deployment option.
	// +kubebuilder:validation:Enum=KubeVirt;None;External
	// +kubebuilder:default=KubeVirt
	// +optional
	Type KubeVirtCSIDriverType `json:"type,omitempty"`

	// InfraStorageClass is the StorageClass on the infra cluster used to back
	// tenant PersistentVolumeClaims. Required when Type is KubeVirt.
	// +optional
	InfraStorageClass string `json:"infraStorageClass,omitempty"`
}

func init() {
	SchemeBuilder.Register(&OpenshiftAssistedControlPlane{}, &OpenshiftAssistedControlPlaneList{})
}

// GetConditions returns the set of conditions for this object.
func (in *OpenshiftAssistedControlPlane) GetConditions() []metav1.Condition {
	return in.Status.Conditions
}

// SetConditions sets the conditions on this object.
func (in *OpenshiftAssistedControlPlane) SetConditions(conditions []metav1.Condition) {
	in.Status.Conditions = conditions
}
